### ISSUE TITLE
Undefined function error

### ISSUE THREAD

**Issue by michael-chaplin-gmcvo** [compucorp/webform_civicrm_postcode#5]
When trying to change a textfield in a webform to a postcode widget, it fails with an error:

Error: Call to undefined function wf_crm_tokeninput_path() in _webform_edit_civipostcode() (line 8 of /home/XXXXXX/public_html/sites/all/modules/webform_civicrm_postcode/includes/civipostcode_component.inc).

Have updated webform + webform_civicrm to latest. PHP = 7.1.

**Comment by michael-chaplin-gmcvo** [comment]
Fixed the above bug:

/public_html/sites/all/modules/webform_civicrm_postcode/includes/civipostcode_component.inc 

function _webform_edit_civipostcode($component) {
//dsm(module_exists('webform_civicrm'));//returns 1
// new line follows, allows this module to find function wf_crm_tokeninput_path
module_load_include('inc', 'webform_civicrm', 'includes/contact_component');

$form = array();
$form['#attached']['js'][] = wf_crm_tokeninput_path();
return $form;
}

**Comment by Shubham-Compucorp** [comment]
@mikantchap the issue has now been fixed and merged to master.
